# Generated by Django 4.2.13 on 2025-07-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_weightlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField()),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('live_births', models.IntegerField(blank=True, null=True)),
                ('dead_births', models.IntegerField(blank=True, null=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproduction_events_female', to='core.animal')),
                ('male', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproduction_events_male', to='core.animal')),
            ],
        ),
    ]
