# Generated by Django 4.2.13 on 2025-07-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_healthlog_medication_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('type', models.CharField(choices=[('Costo', 'Costo'), ('Ingreso', 'Ingreso')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, help_text='ID of related entity like Animal, Location, etc.', null=True)),
            ],
        ),
    ]
