# Generated by Django 4.2.13 on 2025-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
