# Generated by Django 4.2.13 on 2025-07-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feedinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feedinventory')),
                ('feed_ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feedration')),
            ],
        ),
    ]
